export const UPDATE_LIST_ITEM = "UPDATE_LIST_ITEM";
export const ADD_NEW_CATTEGORY = "ADD_NEW_CATTEGORY";
export const DELETE_CATTEGORY = "DELETE_CATTEGORY";
export const DELETE_CATTEGORY_ITEM = "DELETE_CATTEGORY_ITEM";
